# Generated by Django 3.2.2 on 2021-05-13 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_profile_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('PINTEREST', 'Pinterest'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn')], max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
