# Generated by Django 3.2.2 on 2021-05-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_socialmediaurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaurl',
            name='site',
            field=models.CharField(blank=True, choices=[('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('PINTEREST', 'Pinterest'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub')], max_length=20, null=True),
        ),
    ]
